domain                             = "localhost"
insecure                           = "true"
port                               = "8081"
xpanse-ui_base_uri                 = "http://localhost:3000"
xpanse_swagger-ui_base_uri         = "http://localhost:8080"
terraform-boot_swagger-ui_base_uri = "http://localhost:9090"
tofu-maker_swagger-ui_base_uri     = "http://localhost:9092"
auth_token_type                    = "JWT"